Manual side feature
mazid1/ngx-mzd-timeline pull request #10
Opened 2021-06-01 17:47 UTC by oliveroing

I added a new feature: you can set manualSide property true and then set the property leftSide (in the child component) true or false in order to select the position of the children. That feature has priority above the alternateSide property. With this feature you can select the side of each child.

I also upload the /dist folder because previously I tried to implement the library myself but i couldn't do it succesfully.

Can you approve the pull request?

2021-06-01 19:03 UTC, mazid1 commented
You should not commit `dist` folder. It should be in `.gitignore` file.

2021-06-01 19:06 UTC, oliveroing commented
Done!

2021-06-01 19:15 UTC, mazid1 commented
Thank you. It is 1:15am here. I'll review tomorrow when I get time.

2021-06-01 19:24 UTC, oliveroing commented
Ok! Thank you very much! I'll be waiting for news! See you!

2021-12-29 13:58 UTC, neryortez commented
Hi there
Can this be merged  ?

2022-02-11 14:21 UTC, mazid1 requested changes
Please remove `node_modules` directory from `projects/ngx-mzd-timeline` directory.

2022-02-11 14:21 UTC, mazeduldev commented on projects/ngx-mzd-timeline/node_modules/tslib/CopyrightNotice.txt
> +/*! *****************************************************************************
Could you please remove this entire `node_modules` folder from the PR.

2022-10-12 17:35 UTC, soniclvr811 commented
has this been pulled

2022-10-12 17:56 UTC, mazeduldev commented
@soniclvr811 I could not merge it because of so many conflicts and the entire node_modules was committed. Anyway, this pr is actually too old to resolve conflicts. I think, it will be easier to re-implement this feature.

2025-07-01 19:18 UTC, mazeduldev commented
Closing due to inactivity

2025-07-01 19:18 UTC, closed without merging